# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a70c00a0443784296a84296a97bf54fe310bf570687971d1bfd09827d33764304fb6278fa9598ab2337513bca87377dc5643747943224b3f1e5eeebb269e2510

test:
  secret_key_base: 977b086a6819c507ead4ec41de2cc3e00d9a065cace78c833ac800393042e24e43e594824bd8204bc7e2b7681f932bc30f14fd8bd9a91d7f6de9bcb8f0b2800c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
